Fix issues
TownSquareXYZ/tonconnect-ui-vue pull request #10
Opened 2024-09-08 13:29 UTC by sansx

1. optimize TonConnectUIProvider

2. use Symble key in provide / inject
```
// now we use tonConnectUIKey export from @townsquarexyz/ui-vue to inject instance in demo project, like this usage
<script  lang="ts">
import { TonConnectUI, useTonWallet, tonConnectUIKey } from "@townsquarexyz/ui-vue";
const tonConnectUI = inject<TonConnectUI | null>(tonConnectUIKey, null);
</script>
```

which related to #8 [Moderate] implementation 1, 2, 3, 4

2024-09-19 04:16 UTC, dnischeta requested changes

2024-09-19 04:16 UTC, dnischeta commented on src/components/TonConnectUIProvider.vue
>  <script lang="ts">
Wait, provider is implemented incorrect. I see, why.

In the issue I put next example of code:

```
// <TonConnectUIProvider />
const tonConnectUI = shallowRef<TonConnectUI | null>(null);

provide('ton-connect-ui', tonConnectUI);

// Injection consumer, for example `useTonWallet`
const tonConnectUi = inject('ton-connect-ui'); // That line of code should be inside `useTonConnectUI`, put it here for simplification
const unsub = shallowRef<() => void>(() => {});
const wallet = shallowRef<...>(null);

onMounted(() => {
  watch(tonConnectUI, (actualTonConnectUI) => {
    unsub(); // Unsubscribe on watcher trigger <-> when tonConnectUI instance is updated (as done in React)

    wallet.value = actualTonConnectUI.wallet;

    unsub.value = actualTonConnectUI.onStatusChange((value) => {
      wallet.value = value;
    });
  });
});

onUnmounted(() => {
  unsub.value();
});
```

Pay attention to the comment `// Injection consumer, for example `useTonWallet``. So all next code should be placed into `useTonWallet`.

2024-09-19 04:16 UTC, dnischeta commented on src/components/TonConnectUIProvider.vue
> +    provide(tonConnectUIKey, tonConnectUI.value);
Actually, as I see above, `tonConnectUI.value.uiOptions` are updated using watch. So instance of TonConnectUI is the same. Therefore, you don't need to subscribe for `tonConnectUI.value` updates in consumers (eg. useTonWallet).

So just remove useless code from that component (`wallet`, `unsubscribe`, etc.)

2024-10-06 16:01 UTC, dnischeta approved these changes
I suppose, you can move forward to the testing and preparing for the release.

2024-10-07 13:07 UTC, sansx commented on README.md
> +`<TonConnectButton :button-root-id="`ton-connect-button`" />`
done

2024-10-07 16:38 UTC, dnischeta commented
> feel free to notify Alex that the repo is ready to merge

Am I entitled to do it? I mean, he asked me to do a general review. We can clear everything up in Telegram.

> Also, could we connect on Telegram for smoother communication?

Feel free to contact on Telegram: https://t.me/dimchickLoveNY .

2024-10-08 15:18 UTC, sansx commented
Yeah, since Alex asked you to handle the general review, we’d like to let you inform him to keep the process smooth and complete, and then we can push this into next step. And it's not the must, we can let him know this in some other day. :D

2024-10-08 15:18 UTC, merged